### ISSUE TITLE
Some tests fail on windows using venv when running pytest but pass when running python -m pytest

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#62]
Some tests fail on windows using venv when running pytest but pass when running python -m pytest. Maybe we just update instructions in the readme?

This seems to be a known issue:
https://github.com/pytest-dev/pytest/issues/2564

**Comment by MichaelClerx** [comment]
Can you verify that both pytest versions are the same ones? For example, when you type `pytest` are you calling a system-wide executable rather than the local one?

And could you give the output for the failed tests?

**Comment by MauriceHendrix** [comment]
### (venv) C:\Users\uczmh2\Desktop\venv\cellmlmanip>python -m pytest
============================= test session starts =============================
platform win32 -- Python 3.7.4, pytest-3.2.0, py-1.4.34, pluggy-0.4.0
rootdir: C:\Users\uczmh2\Desktop\venv\cellmlmanip, inifile:
collected 77 items

tests\test_hodgkin.py ..........
tests\test_mathml2sympy.py ..............................................
tests\test_parser.py ........s......
tests\test_rdf.py ..
tests\test_units.py ....

==================== 76 passed, 1 skipped in 3.22 seconds =====================

### (venv) C:\Users\uczmh2\Desktop\venv\cellmlmanip>pytest
============================= test session starts =============================
platform win32 -- Python 3.7.4, pytest-3.2.0, py-1.4.34, pluggy-0.4.0
rootdir: C:\Users\uczmh2\Desktop\venv\cellmlmanip, inifile:
collected 0 items / 5 errors

=================================== ERRORS ====================================
___________________ ERROR collecting tests/test_hodgkin.py ____________________
ImportError while importing test module 'C:\Users\uczmh2\Desktop\venv\cellmlmanip\tests\test_hodgkin.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_hodgkin.py:7: in <module>
    from cellmlmanip import load_model
E   ImportError: cannot import name 'load_model' from 'cellmlmanip' (unknown location)
_________________ ERROR collecting tests/test_mathml2sympy.py _________________
ImportError while importing test module 'C:\Users\uczmh2\Desktop\venv\cellmlmanip\tests\test_mathml2sympy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_mathml2sympy.py:7: in <module>
    from cellmlmanip import mathml2sympy
E   ImportError: cannot import name 'mathml2sympy' from 'cellmlmanip' (unknown location)
____________________ ERROR collecting tests/test_parser.py ____________________
ImportError while importing test module 'C:\Users\uczmh2\Desktop\venv\cellmlmanip\tests\test_parser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_parser.py:6: in <module>
    from cellmlmanip import load_model, parser
E   ImportError: cannot import name 'load_model' from 'cellmlmanip' (unknown location)
_____________________ ERROR collecting tests/test_rdf.py ______________________
ImportError while importing test module 'C:\Users\uczmh2\Desktop\venv\cellmlmanip\tests\test_rdf.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_rdf.py:7: in <module>
    import cellmlmanip.rdf
E   ModuleNotFoundError: No module named 'cellmlmanip.rdf'
____________________ ERROR collecting tests/test_units.py _____________________
ImportError while importing test module 'C:\Users\uczmh2\Desktop\venv\cellmlmanip\tests\test_units.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_units.py:4: in <module>
    from cellmlmanip.model import MetaDummy
E   ModuleNotFoundError: No module named 'cellmlmanip.model'
!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 5 error in 1.13 seconds ===========================

(venv) C:\Users\uczmh2\Desktop\venv\cellmlmanip>

**Comment by tamuri** [comment]
Installing the cellmlmanip package using `pip install -e .` should fix it.

**Comment by MauriceHendrix** [comment]
This makes it worse: pytest still fails and puthon-m pytest now also

`
(venv) c:\Users\uczmh2\Desktop\venv\cellmlmanip>pip install -e .
Obtaining file:///C:/Users/uczmh2/Desktop/venv/cellmlmanip
Collecting lxml>=4 (from cellmlmanip==0.0.1)
  Using cached https://files.pythonhosted.org/packages/20/8e/f9c5042b5526b732d9e6c9402d87659584448d020b16a889a07f7f0eb0a8/lxml-4.4.1-cp37-cp37m-win32.whl
Collecting networkx>=2 (from cellmlmanip==0.0.1)
Collecting pint>=0.8.1 (from cellmlmanip==0.0.1)
  Using cached https://files.pythonhosted.org/packages/15/9d/bf177ebbc57d25e9e296addc14a1303d1e34d7964af5df428a8332349c42/Pint-0.9-py2.py3-none-any.whl
Collecting rdflib>=4 (from cellmlmanip==0.0.1)
  Using cached https://files.pythonhosted.org/packages/3c/fe/630bacb652680f6d481b9febbb3e2c3869194a1a5fc3401a4a41195a2f8f/rdflib-4.2.2-py3-none-any.whl
Collecting sympy==1.1.1 (from cellmlmanip==0.0.1)
Requirement already satisfied: decorator>=4.3.0 in c:\users\uczmh2\desktop\venv\lib\site-packages (from networkx>=2->cellmlmanip==0.0.1) (4.3.0)
Collecting pyparsing (from rdflib>=4->cellmlmanip==0.0.1)
  Using cached https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
Requirement already satisfied: isodate in c:\users\uczmh2\desktop\venv\lib\site-packages (from rdflib>=4->cellmlmanip==0.0.1) (0.6.0)
Collecting mpmath>=0.19 (from sympy==1.1.1->cellmlmanip==0.0.1)
Requirement already satisfied: six in c:\users\uczmh2\desktop\venv\lib\site-packages (from isodate->rdflib>=4->cellmlmanip==0.0.1) (1.10.0)
Installing collected packages: lxml, networkx, pint, pyparsing, rdflib, mpmath, sympy, cellmlmanip
  Running setup.py develop for cellmlmanip
Successfully installed cellmlmanip lxml-4.4.1 mpmath-1.1.0 networkx-2.3 pint-0.9 pyparsing-2.4.2 rdflib-4.2.2 sympy-1.1.1
`

`
(venv) c:\Users\uczmh2\Desktop\venv\cellmlmanip>pip freeze
-e git+https://github.com/ModellingWebLab/cellmlmanip.git@a2b6a793068d9483d8e256502db5cc4527f0e074#egg=cellmlmanip
click==6.7
decorator==4.3.0
flake8==3.5.0
isodate==0.6.0
isort==4.2.15
lxml==4.4.1
mccabe==0.6.1
mpmath==1.1.0
networkx==2.3
Pint==0.9
pycodestyle==2.3.1
pyflakes==1.6.0
pyparsing==2.4.2
rdflib==4.2.2
six==1.10.0
sympy==1.1.1
`

`
(venv) c:\Users\uczmh2\Desktop\venv\cellmlmanip>pytest
============================= test session starts =============================
platform win32 -- Python 3.7.4, pytest-3.2.0, py-1.4.34, pluggy-0.4.0
rootdir: c:\Users\uczmh2\Desktop\venv\cellmlmanip, inifile:
collected 0 items / 5 errors

=================================== ERRORS ====================================
___________________ ERROR collecting tests/test_hodgkin.py ____________________
ImportError while importing test module 'c:\Users\uczmh2\Desktop\venv\cellmlmanip\tests\test_hodgkin.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_hodgkin.py:7: in <module>
    from cellmlmanip import load_model
E   ModuleNotFoundError: No module named 'cellmlmanip'
_________________ ERROR collecting tests/test_mathml2sympy.py _________________
ImportError while importing test module 'c:\Users\uczmh2\Desktop\venv\cellmlmanip\tests\test_mathml2sympy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_mathml2sympy.py:7: in <module>
    from cellmlmanip import mathml2sympy
E   ModuleNotFoundError: No module named 'cellmlmanip'
____________________ ERROR collecting tests/test_parser.py ____________________
ImportError while importing test module 'c:\Users\uczmh2\Desktop\venv\cellmlmanip\tests\test_parser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_parser.py:6: in <module>
    from cellmlmanip import load_model, parser
E   ModuleNotFoundError: No module named 'cellmlmanip'
_____________________ ERROR collecting tests/test_rdf.py ______________________
ImportError while importing test module 'c:\Users\uczmh2\Desktop\venv\cellmlmanip\tests\test_rdf.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_rdf.py:6: in <module>
    import cellmlmanip
E   ModuleNotFoundError: No module named 'cellmlmanip'
____________________ ERROR collecting tests/test_units.py _____________________
ImportError while importing test module 'c:\Users\uczmh2\Desktop\venv\cellmlmanip\tests\test_units.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_units.py:4: in <module>
    from cellmlmanip.model import MetaDummy
E   ModuleNotFoundError: No module named 'cellmlmanip'
!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 5 error in 1.13 seconds ===========================
`

`
(venv) c:\Users\uczmh2\Desktop\venv\cellmlmanip>python -m pytest
c:\Users\uczmh2\Desktop\venv\Scripts\python.exe: No module named pytest
`

**Comment by tamuri** [comment]
Bizarre. I have no idea why it would cause pytest to disappear.

**Comment by jonc125** [comment]
Seems like we should just update the docs to say use `python -m pytest` on Windows!

**Comment by MauriceHendrix** [comment]
latest merge fixed it both pytest and python -m pytest work for me on windows now
